require 'active_support/all'
require './lib/geometry_parser/point'
require './lib/geometry_parser/segment'
require './lib/geometry_parser/convex_hull'
require './lib/geometry_parser/polygon'
require './lib/geometry_parser/convex_polygon'
require './lib/geometry_parser/cli'